apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bonus-advisor-agent
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "1"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: bonus-agent-sa@jrodriguez-sandbox.iam.gserviceaccount.com
      containers:
        - image: gcr.io/jrodriguez-sandbox/bonus-advisor-agent:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PROJECT_ID
              value: "jrodriguez-sandbox"
            - name: REGION
              value: "us-central1"
            - name: GOOGLE_CLOUD_PROJECT
              value: "jrodriguez-sandbox"
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 3
